config/routes.rb
ZakResume::Application.routes.draw do
  root to: "pages#index"
  resources :pages, only: [:index]
  post "/contact_mailers", to: "contact_mailers#deliver_contact", as: "deliver"
  post "/chats/receive", to: "chats#receive"
  post "/chats/send_out", to: "chats#send_out"
  get "/chats/all", to: "chats#all_chats"
  post "/chats/destroy_all_chats", to: "chats#destroy_all_chats"
end

app/models/chat.rb
class Chat < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  skip_before_action :verify_authenticity_token

  def receive
    puts "made it to receive"
		Chat.create!(from: 1, to: 2, chat: params['Body'])

    message_body = params["Body"]
    from_number = params["From"]

    SMSLogger.log_text_message from_number, message_body
		render json: params['body']
  end

  def send_out

  	puts params



    Chat.create!(from: 2,to: 1, chat: params["body"])

  	client = Twilio::REST::Client.new 'AC035e8397a69c77b3b8e9114cd1874b76', '182b2d908203f792b47b71a403bb30cc'

  	message = client.messages.create from: '2059286659', to: '2068532262', body: params['body']
  	render plain: message.status

  end




  def all_chats
    render json: Chat.last(5)
  end

  def destroy_all_chats
    Chat.all.each do |post|
      post.destroy
    end
    render json: "chats deleted"
  end


end

app/controllers/contact_mailers_controller.rb
class ContactMailersController < ApplicationController
  def deliver_contact
    ContactMailer.contact_email(params[:email]).deliver
    flash[:notice] = "Your message has been sent!"
    redirect_to pages_url
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    type = request.env['HTTP_USER_AGENT']
    @videotype = ( type.include?("Mozilla") ? ["ogg", "moz"] : ["mov", "other"])

  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def root
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def form_auth
    <<-HTML.html_safe
      <input
      type="hidden"
      name="authenticity_token"
      value="#{ form_authenticity_token }">
    HTML
  end
  
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/contact_mailers_helper.rb
module ContactMailersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ZakResume</title>
  <link href='http://fonts.googleapis.com/css?family=Merriweather&subset=cyrillic-ext,latin' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Lato:400,900' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div>
  <% if flash[:notice] %>
<ul id="notice" class="notice">
  <li><%= flash[:notice] %></li>
</ul>
  <% end %>
</div>

<%= yield %>
</body>
</html>

app/views/pages/_about.html.erb
<section id="about" data-id="-195" class="hidden">
  <p>
    I started creating static websites for my busniess and enjoyed creating them so much that I continued to learn.
  </p>
  <p>
    I have experience in Ruby on Rails, Javascript, Backbone, node, SQL, HTML, and CSS. I have built numerous projects including a KickStarter clone built in Rails and Backbone, and the game Asteroids built in canvas.
  </p>
  <p>
    In my former occupations I worked as Operations Manager for chain of mattress stores and later as Owner Operater of Four Corners Funiture in Seattle, Wa.
  </p>

  <%= render "social" %>
</section>

app/views/pages/_asteroids_model.html.erb
<div id="game-window" class="hidden">

  <div id="game-container">
    <div>
      <div>
        <p>
          Asteroids!
        </p>
      </div>
    <figure for="game-canvas">&times;</figure>
    <canvas id="game-canvas"></canvas>
    <div id="explanation">
      <p>
        Use arrow keys to navigate and the space bar to fire
      </p>
    </div>
  </div>
  </div>
</div>

app/views/pages/_contact.html.erb
<section id="contact" class="hidden" data-id="<%= @videotype[1] == "moz" ? -390 : -385 %>">

  <p>
    Contact me by email with the form below or at zakstal@gmail.com. You can also send me a text via twilio by clicking on "text me" in the upper left hand corner.
  </p>


  <form class="group" action="<%= deliver_url %>" method="post">
    <%= form_auth %>
  <input type="text" placeholder="From:" name="email[contact_email]" value="">
  <input type="hidden" name="email[zak_eamil]" value="zakstal@gmail.com">
  <input type="submit" id="submit" value="Send">

    <textarea name="email[body]" rows="8" cols="40" placeholder="Email me"></textarea>
  </form>

  <%= render "social" %>

</section>

app/views/pages/_intro.html.erb
<section id="intro" data-id="-100" class="">

    <div id="my-image">
      <%= image_tag('zachary-stallings.jpg') %>
    </div>

  <p>
    Hi! I'm a web developer in the New York area with experience in Ruby on Rails and Javascript. I have a background in retail furniture and visual art. Take a look at my coding projects or browse my resume. I would love to hear from you so drop me a line.

  </p>

  <%= render "social" %>
</section>

app/views/pages/_navigation.html.erb
<section id="head-window">
    <ul id="head-nav">
      <li id="nav-header">NIL</li>
      <li id="nav-header">Intro</li>
      <li id="nav-header">About Me</li>
      <li id="nav-header">Projects</li>
      <li id="nav-header">Contact</li>
      <li id="nav-header">Resume</li>
    </ul>
  </section>
  <div id="all-content">

<div id="face"></div>
<div id="social">
  <div class="list">
    <a href="https://github.com/zakstal" class="list-item"><%= image_tag("github.png") %></a>
    <a href="mailto:zakstal@gmail.com" class="list-item"><%= image_tag("mail_small.png") %></a>
    <a href="https://www.linkedin.com/pub/zachary-stallings/a8/4b3/384/" class="list-item"><%= image_tag("linkedin.png") %></a>
  </div>
</div>
<ul class="side-nav" id="side-navigation">
  <li class="side-nav-li" id="intro-tab" data-id="intro">Intro</li>
  <li class="side-nav-li" id="about-tab" data-id="about">About</li>
  <li class="side-nav-li" id="project-tab" data-id="projects">Projects</li>
  <li class="side-nav-li resume-link" id="resume-tab" data-id="resume">Resume</li>
  <li class="side-nav-li" id="contact-tab" data-id="contact">Contact</li>

</ul>

app/views/pages/_projects.html.erb
<section id="projects" class="hidden" data-id="<%= @videotype[1] == "moz" ? -295 :-285 %>">
  <h2>Projects</h2>
  <p>
      Here are a few projects I have worked on. Hover over the image to see a short clip of the project in action.
  </p>

  <div class="project">
    <a href="http://ksclone.herokuapp.com/" class="project-image"><%= video_tag("kickstarter.#{@videotype[0]}") %></a>
  <div class="live-git">
      <a href="https://github.com/zakstal/KickStarterClone"  class="project-links" ><h2>git</h2></a>|<a href="http://ksclone.herokuapp.com/" class="project-links" ><h2>live</h2></a>
    </div>
    <p>A clone of one of my favorite websites kickstarter. You can create a campaign and pledge to you favorite projects. </p>
  </div>

  <div class="project">
    <div src="" class="project-image" id="asteroids"><%= video_tag("asteroids.#{@videotype[0]}") %></div>
    <div class="live-git">
      <a href="https://github.com/zakstal/asteroid-game"  class="project-links" ><h2>git</h2></a>|<a href="#" id="asteroids-link" class="project-links" ><h2>live</h2></a>
    </div>
    <p>Asteroids! This project was created with canvas. Fly around space destroying asteroids. Just dont get crushed!</p>
  </div>

  <div class="project">
    <a href="https://github.com/zakstal/Chess" class="project-image"><%= video_tag("chess.#{@videotype[0]}") %></a>
    <div class="live-git">
      <a href="https://github.com/zakstal/Chess"  class="project-links" ><h2>git</h2></a>
    </div>
    <p>Chess. Play against an opponent, make valid moves and checkmate the king. To play, clone the repo, navigate to the file in your command line, and open enter ruby Game.rb.</p>
  </div>

  <%= render "social" %>

</section>

app/views/pages/_resume.html.erb
<section id="resume" class="hidden" data-id="<%= @videotype[1] == "moz" ? -485 :-470 %>">
  <p>
    please click to view my resume
  </p>
  <h2 class="resume-link">Resume</h2>
  <a href="https://docs.google.com/document/d/1TeuIacgTXeZk8xGcJuSvss-Htjzyocc_BlU_2Jp3zcI/export?format=pdf"><h3>Download my resume</h3></a>
</section>

app/views/pages/_resume_model.html.erb
<div id="resume-window" class="hidden">

  <div id="resume-container">
    <div>
      <a id="download-my-resume" href="https://docs.google.com/document/d/1TeuIacgTXeZk8xGcJuSvss-Htjzyocc_BlU_2Jp3zcI/export?format=pdf"><h3>Download my resume</h3></a>
    <div id="resume-close" for="resume-show">&times;</div>
    <div id="resume-show">
      <iframe src="https://docs.google.com/document/d/1TeuIacgTXeZk8xGcJuSvss-Htjzyocc_BlU_2Jp3zcI/pub?embedded=true"></iframe>
    </div>


  </div>
  </div>
</div>

app/views/pages/_social.html.erb
<div id="large-icon-contact group">
  <a href="https://github.com/zakstal" class="large-icon"><%= image_tag("git_big_blue.png") %></a>
  <a href="https://www.linkedin.com/pub/zachary-stallings/a8/4b3/384/" class="large-icon"><%= image_tag("in_big_blue.png") %></a>
  <a href="mailto:zakstal@gmail.com" class="large-icon"><%= image_tag("mail_big_blue.png") %></a>
</div>

app/views/pages/_text.html.erb
<div id="text-tab-click">

</div>

<div id="text-window">
  <div id="text-frame">

  </div>
</div>
<form id="text-form">


<input type="text" name="some_name" class="text-message-hide" id="text-message-out">
<button type="submit" class="text-message-submit-hide" id="text-message-submit" name="some_name" value="">
  <div id="send-send-text">
    <span>S</span>
    <span>E</span>
    <span>N</span>
    <span>D</span>
  </div>
</button>
</form>
<div id="text-tab" class="text-tab-left group">

</div>



<div id="text-me">
  <span id="c1" data-id="off" class="c1 text-me-style">T</span>
  <span id="c2" class="text-me-style c2">E</span>
  <span id="c3" class="text-me-style c3">X</span>
  <span id="c4" class="text-me-style c4">T</span>
  <!-- <span id="c5" class="text-me-style c5"> </span> -->
  <span id="c6" class="text-me-style c6">M</span>
  <span id="c7" class="text-me-style c7">E</span>
</div>

app/views/pages/index.html.erb
<div id="container-all">
<%= render "resume_model" %>
<%= render "asteroids_model" %>

<main>

<%= render "text" %>

    <div id="buffer"></div>

    <%= render "navigation" %>

    <div id="title">
      <span class="dev-tag">Web Developer</span>
      <h1>Zachary Stallings</h1>
    </div>

    <%= render "intro" %>

    <%= render "about" %>

    <%= render "projects" %>

    <%= render "contact" %>

    <%= render "resume" %>
  </div>
</main>

</div>

<script charset="utf-8">

  var backgroundImage = "<%= asset_path('outer-space.jpg') %>";
  var canvasEl = document.getElementById("game-canvas");
  var canvasHeight = canvasEl.height = window.innerHeight;
  var canvasWidth = canvasEl.width = window.innerWidth;
  var ctx = canvasEl.getContext("2d");
  var ast = new Asteroids.GameView(ctx, canvasHeight, canvasWidth);
  var image = document.getElementById("image-back")
  ast.start(backgroundImage);

</script>